# Generated by Django 3.1 on 2020-09-25 21:39

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authName', models.CharField(max_length=32, unique=True, verbose_name='权限名称')),
                ('path', models.CharField(max_length=255, verbose_name='URL')),
                ('level', models.IntegerField(verbose_name='权限等级')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='Rbac.permission', verbose_name='父级菜单')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认角色', max_length=32, verbose_name='角色')),
                ('code', models.CharField(default='master', max_length=32, verbose_name='编码')),
                ('desc', models.TextField(blank=True, verbose_name='角色描述')),
                ('permissions', models.ManyToManyField(blank=True, to='Rbac.Permission', verbose_name='permissions')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('name', models.CharField(default='', max_length=50, verbose_name='姓名')),
                ('mobile', models.CharField(default='186000000000', max_length=12, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('is_staff', models.BooleanField(default=True, verbose_name='员工')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建日期')),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新日期')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, to='Rbac.Role', verbose_name='角色')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='更新日期')),
                ('expiration_time', models.DateTimeField(auto_now_add=True, verbose_name='失效时间')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户token表',
                'verbose_name_plural': '用户token表',
            },
        ),
    ]
